# Generated by Django 2.2.3 on 2019-08-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_comment_re'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='blog',
        ),
    ]
